version: '3.7'
services:
 app:
   image: eu.gcr.io/nice-root-258809/app:${BUILD_NUMBER} 
   build:
    context: ./
    dockerfile: Dockerfile
   ports:
        - target: 5000
          published: 5000
          protocol: tcp
   environment:
        - MY_SQL_USER=${MY_SQL_USER}
        - MY_SQL_PASS=${MY_SQL_PASS}
        - MY_SQL_HOST=${MY_SQL_HOST}
        - MY_SQL_DB=${MY_SQL_DB}
        - MY_SQL_DB_TEST=${MY_SQL_DB_TEST}
        - KEY=${KEY}

